<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-10-13 12:12

$extensionPath = t3lib_extMgm::extPath('addthis');
return array(
    'tx_addthis_controller_buttonscontroller' => $extensionPath . 'Classes/Controller/ButtonsController.php',
    'tx_addthis_viewhelpers_rawvalueviewhelper' => $extensionPath . 'Classes/ViewHelpers/RawValueViewHelper.php',
    'tx_addthis_codegenerator' => $extensionPath . 'Classes/CodeGenerator.php',
    'tx_addthis_config' => $extensionPath . 'Classes/Config.php',
    'tx_addthis_configreader' => $extensionPath . 'Classes/ConfigReader.php',
    'tx_addthis_metatags' => $extensionPath . 'Classes/Metatags.php',
    'tx_addthis_wizard' => $extensionPath . 'Classes/Wizard.php',
);
